"""schema inicial completo

Revision ID: 69c4df361ee9
Revises: 
Create Date: 2026-05-18 18:31:11.429545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '69c4df361ee9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_acessos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('profissional_id', sa.UUID(), nullable=False),
    sa.Column('unidade_id', sa.UUID(), nullable=True),
    sa.Column('cpf_hash', sa.String(length=64), nullable=True),
    sa.Column('tipo_acesso', sa.String(length=50), nullable=False),
    sa.Column('justificativa', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consulta_relato',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_consulta', sa.UUID(), nullable=False),
    sa.Column('relato_texto', sa.Text(), nullable=True),
    sa.Column('registrado_por', sa.UUID(), nullable=False),
    sa.Column('registrado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_consulta')
    )
    op.create_table('consulta_resultado',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_consulta', sa.UUID(), nullable=False),
    sa.Column('score_geral', sa.SmallInteger(), nullable=False),
    sa.Column('faixa_risco', sa.String(length=20), nullable=False),
    sa.Column('indicadores', sa.JSON(), nullable=False),
    sa.Column('resumo_ia', sa.Text(), nullable=True),
    sa.Column('sentimento_voz', sa.JSON(), nullable=True),
    sa.Column('calculado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sumario_estruturado', sa.JSON(), nullable=True),
    sa.Column('texto_clinico', sa.Text(), nullable=True),
    sa.Column('fontes_utilizadas', sa.JSON(), nullable=True),
    sa.Column('tokens_utilizados', sa.Integer(), nullable=True),
    sa.Column('prompt_enviado', sa.Text(), nullable=True),
    sa.Column('resposta_bruta_llm', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_consulta')
    )
    op.create_table('consulta_triagem',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('id_consulta', sa.UUID(), nullable=False),
    sa.Column('peso_kg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('pa_sistolica', sa.SmallInteger(), nullable=False),
    sa.Column('pa_diastolica', sa.SmallInteger(), nullable=False),
    sa.Column('registrado_por', sa.UUID(), nullable=False),
    sa.Column('registrado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_consulta')
    )
    op.create_table('consultas_identidade',
    sa.Column('id_consulta', sa.UUID(), nullable=False),
    sa.Column('paciente_id', sa.UUID(), nullable=False),
    sa.Column('profissional_id', sa.UUID(), nullable=False),
    sa.Column('ubs_id', sa.UUID(), nullable=True),
    sa.Column('estado_id', sa.String(length=10), nullable=True),
    sa.Column('tipo_consulta', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('dum', sa.Date(), nullable=True),
    sa.Column('ig_semanas', sa.SmallInteger(), nullable=True),
    sa.Column('ig_dias', sa.SmallInteger(), nullable=True),
    sa.Column('triagem_concluida', sa.Boolean(), nullable=False),
    sa.Column('triagem_concluida_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('medico_id', sa.UUID(), nullable=True),
    sa.Column('assumida_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('aberta_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('encerrada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analise_concluida_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analise_erro', sa.Text(), nullable=True),
    sa.Column('analise_revisada', sa.Boolean(), nullable=False),
    sa.Column('analise_revisada_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('analise_revisada_por', sa.UUID(), nullable=True),
    sa.Column('encaminhado', sa.Boolean(), nullable=False),
    sa.Column('encaminhado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('encaminhado_por', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id_consulta')
    )
    op.create_table('historico_peso',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paciente_id', sa.UUID(), nullable=False),
    sa.Column('id_consulta', sa.UUID(), nullable=False),
    sa.Column('peso_kg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('registrado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_consulta')
    )
    op.create_table('pacientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cpf_hash', sa.String(length=64), nullable=False),
    sa.Column('cns', sa.String(length=20), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('estado_civil', sa.String(length=20), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('possui_filhos', sa.Boolean(), nullable=False),
    sa.Column('quantidade_filhos', sa.SmallInteger(), nullable=True),
    sa.Column('altura_cm', sa.SmallInteger(), nullable=False),
    sa.Column('endereco', sa.String(length=500), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cns'),
    sa.UniqueConstraint('cpf_hash')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('MEDICO', 'ENFERMEIRO', 'ADMIN', name='roleenum'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.execute("""
        CREATE OR REPLACE FUNCTION bloquear_edicao_auditoria()
        RETURNS TRIGGER AS $$
        BEGIN
            RAISE EXCEPTION 'Registros de auditoria não podem ser alterados ou removidos.';
        END;
        $$ LANGUAGE plpgsql
    """)
    op.execute("DROP TRIGGER IF EXISTS audit_imutavel ON audit_acessos")
    op.execute("""
        CREATE TRIGGER audit_imutavel
        BEFORE UPDATE OR DELETE ON audit_acessos
        FOR EACH ROW EXECUTE FUNCTION bloquear_edicao_auditoria()
    """)
    op.create_table('pacientes_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paciente_id', sa.UUID(), nullable=False),
    sa.Column('atualizado_por', sa.UUID(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pacientes_log')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('pacientes')
    op.drop_table('historico_peso')
    op.drop_table('consultas_identidade')
    op.drop_table('consulta_triagem')
    op.drop_table('consulta_resultado')
    op.drop_table('consulta_relato')
    op.execute("DROP TRIGGER IF EXISTS audit_imutavel ON audit_acessos")
    op.execute("DROP FUNCTION IF EXISTS bloquear_edicao_auditoria")
    op.drop_table('audit_acessos')
    # ### end Alembic commands ###
